const Data =  {
    macData: [
        {icon:  'https://www.apple.com/v/mac/home/ac/images/familybrowser/macbook_dark_large.svg', 
         name:  'MacBook'},
        {icon: 'https://www.apple.com/v/mac/home/ac/images/familybrowser/macbookair_dark_large.svg', 
        name:  'MacBook Air'},
        {icon: 'https://www.apple.com/v/mac/home/ac/images/familybrowser/macbookpro_dark_large.svg',
        name:  'MacBook Pro'},
        {icon: 'https://www.apple.com/v/mac/home/ac/images/familybrowser/imac_dark_large.svg',
        name:  'iMac'}, 
        {icon: 'https://www.apple.com/v/mac/home/ac/images/familybrowser/imac_pro_dark_large.svg',
        name:  'iMac Pro'},
        {icon: 'https://www.apple.com/v/mac/home/ac/images/familybrowser/macpro_dark_large.svg',
        name:  'Mac Pro'},
        {icon: 'https://www.apple.com/v/mac/home/ac/images/familybrowser/macmini_dark_large.svg',
        name:  'Mac Mini'},
        {icon: 'https://www.apple.com/v/mac/home/ac/images/familybrowser/mac_acc_dark_large.svg',
        name:  'Accessories'},
        {icon: 'https://www.apple.com/v/mac/home/ac/images/familybrowser/mac_osx_dark_large.svg',
        name:  'Mojave'},
        {icon: 'https://www.apple.com/v/mac/home/ac/images/familybrowser/mac_comp_dark_large.svg',
        name:  'Compare'},
    ],

    ipadData: [
        {icon: 'https://www.apple.com/v/ipad/home/ai/images/home/familybrowser/ipadpro_light_large.svg',
         name: 'iPad Pro'},
        {icon: 'https://www.apple.com/v/ipad/home/ai/images/home/familybrowser/ipad_large.svg',
        name: 'iPad'},
        {icon: 'https://www.apple.com/v/ipad/home/ai/images/home/familybrowser/ipadmini_large.svg',
        name: 'iPad mini 4'},
        {icon: 'https://www.apple.com/v/ipad/home/ai/images/home/familybrowser/ipad_ios10_large.svg',
        name: 'iOS 12'},
        {icon: 'https://www.apple.com/v/ipad/home/ai/images/home/familybrowser/ipad_acc_large.svg',
        name: 'Accessories'},
        {icon: 'https://www.apple.com/v/ipad/home/ai/images/home/familybrowser/ipad_comp_large.svg',
        name: 'Compare'},
    ],

    iphoneData: [
        {icon: 'https://www.apple.com/v/iphone/home/y/images/chapternav/iphonexs_dark_large.svg',
         name: 'iPhone Xs'},
        {icon: 'https://www.apple.com/v/iphone/home/y/images/chapternav/iphonexr_dark_large.svg',
        name: 'iPhone Xr'},
        {icon: 'https://www.apple.com/v/iphone/home/y/images/chapternav/iphone8_dark_large.svg',
        name: 'iPhone 8'},
        {icon: 'https://www.apple.com/v/iphone/home/y/images/chapternav/iphone7_dark_large.svg',
        name: 'iPhone 7'},
        {icon: 'https://www.apple.com/v/iphone/home/y/images/chapternav/ios_dark_large.svg',
        name: 'iOS 12'},
        {icon: 'https://www.apple.com/v/iphone/home/y/images/chapternav/airpods_dark_large.svg',
        name: 'AirPods'},
        {icon: 'https://www.apple.com/v/iphone/home/y/images/chapternav/accessories_dark_large.svg',
        name: 'Accessories'},
        {icon: 'https://www.apple.com/v/iphone/home/y/images/chapternav/compare_dark_large.svg',
        name: 'Compare'},
    ],

    watchData: [
        {icon: 'https://www.apple.com/v/watch/home/k/images/watch_nav_series_2_large.svg',
         name: 'Apple Watch Series 4'},
        {icon: 'https://www.apple.com/v/watch/home/k/images/watch_nav_nike_large.svg',
        name: 'Apple Watch Nike+'},
        {icon: 'https://www.apple.com/v/watch/home/k/images/watch_nav_hermes_large.svg',
        name: 'Apple Watch Hermes'},
        {icon: 'https://www.apple.com/v/watch/home/k/images/watch_nav_edition_large.svg',
        name: 'Apple Watch Series 3'},
        {icon: 'https://www.apple.com/v/watch/home/k/images/watch_nav_watch_os_large.svg',
        name: 'watchOS'},
        {icon: 'https://www.apple.com/v/watch/home/k/images/watch_nav_bands_large.svg',
        name: 'Bands'},
        {icon: 'https://www.apple.com/v/watch/home/k/images/watch_nav_accessories_large.svg',
        name: 'Accessories'},
        {icon: 'https://www.apple.com/v/watch/home/k/images/watch_nav_compare_large.svg',
        name: 'Compare'},
    ],

    tvData: [
        {icon: 'https://www.apple.com/v/tv/home/e/images/home/apple_tv_dark_large.svg',
         name: 'Apple TV 4K'},
        {icon: 'https://www.apple.com/v/tv/home/e/images/home/apple_tv_dark_large.svg',
        name: 'Apple TV'},
        {icon: 'https://www.apple.com/v/tv/home/e/images/home/tvapp_dark_large.svg',
        name: 'TV App'},
        {icon: 'https://www.apple.com/v/tv/home/e/images/home/accessories_dark_large.svg',
        name: 'Accessories'},
        {icon: 'https://www.apple.com/v/tv/home/e/images/home/compare_dark_large.svg',
        name: 'Compare'},
    ],

    musicData: [
        {icon:  'https://www.apple.com/v/music/h/images/overview/icons/apple_music_large.svg', 
         name:  'Apple Music'},
        {icon: 'https://www.apple.com/v/music/h/images/overview/icons/itunes_large.svg', 
        name:  'iTunes'},
        {icon: 'https://www.apple.com/v/music/h/images/overview/icons/homepod_icon_large.svg',
        name:  'HomePod'},
        {icon: 'https://www.apple.com/v/music/h/images/overview/icons/airpods_icon_large.svg',
        name:  'AirPods'}, 
        {icon: 'https://www.apple.com/v/music/h/images/overview/icons/ipod_touch_light_large.svg',
        name:  'iPod Touch'},
        {icon: 'https://www.apple.com/v/music/h/images/overview/icons/accessories_large.svg',
        name:  'Music Accessories'},
        {icon: 'https://www.apple.com/v/music/h/images/overview/icons/gift_cards_large.svg',
        name:  'Gift Cards'},
    ],
}

export default Data;