export const navData = ['Mac', 'iPad', 'iPhone', 'Watch', 'TV', 'Music', 'Support'];

export const subNavData = [
  {
    navitem: 'Mac',
    subname: 'MacBook',
    img: '/images/mac/macbook_dark_large.svg',
    new: false,
  },
  {
    navitem: 'Mac',
    subname: 'MacBook Air',
    img: '/images/mac/macbookair_dark_large.svg',
    new: false,
  },
  {
    navitem: 'Mac',
    subname: 'MacBook Pro',
    img: '/images/mac/macbookpro_dark_large.svg',
    new: true,
  },
  {
    navitem: 'Mac',
    subname: 'iMac',
    img: '/images/mac/imac_dark_large.svg',
    new: false,
  },
  {
    navitem: 'Mac',
    subname: 'iMac Pro',
    img: '/images/mac/imac_pro_dark_large.svg',
    new: false,
  },
  {
    navitem: 'Mac',
    subname: 'Mac Pro',
    img: '/images/mac/macpro_dark_large.svg',
    new: false,
  },
  {
    navitem: 'Mac',
    subname: 'Mac mini',
    img: '/images/mac/macmini_dark_large.svg',
    new: false,
  },
  {
    navitem: 'Mac',
    subname: 'Acccessories',
    img: '/images/mac/mac_acc_dark_large.svg',
    new: false,
  },
  {
    navitem: 'Mac',
    subname: 'Mojave',
    img: '/images/mac/mac_osx_dark_large.svg',
    new: false,
  },
  {
    navitem: 'Mac',
    subname: 'Compare',
    img: '/images/mac/mac_comp_dark_large.svg',
    new: false,
  },
  {
    navitem: 'iPad',
    subname: 'iPad Pro',
    img: '/images/ipad/ipadpro_light_large.svg',
    new: false,
  },
  {
    navitem: 'iPad',
    subname: 'iPad',
    img: '/images/ipad/ipad_large.svg',
    new: true,
  },
  {
    navitem: 'iPad',
    subname: 'iPad mini 4',
    img: '/images/ipad/ipadmini_large.svg',
    new: false,
  },
  {
    navitem: 'iPad',
    subname: 'iOS 12',
    img: '/images/ipad/ipad_ios10_large.svg',
    new: false,
  },
  {
    navitem: 'iPad',
    subname: 'Accessories',
    img: '/images/ipad/ipad_acc_large.svg',
    new: false,
  },
  {
    navitem: 'iPad',
    subname: 'Compare',
    img: '/images/ipad/ipad_comp_large.svg',
    new: false,
  },
  {
    navitem: 'iPhone',
    subname: 'iPhone Xs',
    img: '/images/iphone/iphonexs_dark_large.svg',
    new: true,
  },
  {
    navitem: 'iPhone',
    subname: 'iPhone Xr',
    img: '/images/iphone/iphonexr_dark_large.svg',
    new: true,
  },
  {
    navitem: 'iPhone',
    subname: 'iPhone 8',
    img: '/images/iphone/iphone8_dark_large.svg',
    new: false,
  },
  {
    navitem: 'iPhone',
    subname: 'iPhone 7',
    img: '/images/iphone/iphone7_dark_large.svg',
    new: false,
  },
  {
    navitem: 'iPhone',
    subname: 'iOS 12',
    img: '/images/iphone/ios_dark_large.svg',
    new: false,
  },
  {
    navitem: 'iPhone',
    subname: 'AirPods',
    img: '/images/iphone/airpods_dark_large.svg',
    new: false,
  },
  {
    navitem: 'iPhone',
    subname: 'Accessories',
    img: '/images/iphone/accessories_dark_large.svg',
    new: false,
  },
  {
    navitem: 'iPhone',
    subname: 'Compare',
    img: '/images/iphone/compare_dark_large.svg',
    new: false,
  },
  {
    navitem: 'Watch',
    subname: 'Apple Watch Series 4',
    img: '/images/watch/watch_nav_series_2_large.svg',
    new: true,
  },
  {
    navitem: 'Watch',
    subname: 'Apple Watch Nike+',
    img: '/images/watch/watch_nav_nike_large.svg',
    new: true,
  },
  {
    navitem: 'Watch',
    subname: 'Apple Watch Hermès',
    img: '/images/watch/watch_nav_hermes_large.svg',
    new: true,
  },
  {
    navitem: 'Watch',
    subname: 'Apple Watch Series 3',
    img: '/images/watch/watch_nav_edition_large.svg',
    new: false,
  },
  {
    navitem: 'Watch',
    subname: 'watchOS',
    img: '/images/watch/watch_nav_watch_os_large.svg',
    new: false,
  },
  {
    navitem: 'Watch',
    subname: 'Bands',
    img: '/images/watch/watch_nav_bands_large.svg',
    new: false,
  },
  {
    navitem: 'Watch',
    subname: 'Accessories',
    img: '/images/watch/watch_nav_accessories_large.svg',
    new: false,
  },
  {
    navitem: 'Watch',
    subname: 'Compare',
    img: '/images/watch/watch_nav_compare_large.svg',
    new: false,
  },
  {
    navitem: 'TV',
    subname: 'Apple TV 4K',
    img: '/images/tv/apple_tv_dark_large.svg',
    new: false,
  },
  {
    navitem: 'TV',
    subname: 'Apple TV',
    img: '/images/tv/apple_tv_dark_large.svg',
    new: false,
  },
  {
    navitem: 'TV',
    subname: 'TV App',
    img: '/images/tv/tvapp_dark_large.svg',
    new: false,
  },
  {
    navitem: 'TV',
    subname: 'Accessories',
    img: '/images/tv/accessories_dark_large.svg',
    new: false,
  },
  {
    navitem: 'TV',
    subname: 'Compare',
    img: '/images/tv/compare_dark_large.svg',
    new: false,
  },
  {
    navitem: 'Music',
    subname: 'Apple Music',
    img: '/images/music/apple_music_large.svg',
    new: false,
  },
  {
    navitem: 'Music',
    subname: 'iTunes',
    img: '/images/music/itunes_large.svg',
    new: false,
  },
  {
    navitem: 'Music',
    subname: 'HomePod',
    img: '/images/music/homepod_icon_large.svg',
    new: false,
  },
  {
    navitem: 'Music',
    subname: 'AirPods',
    img: '/images/music/airpods_icon_large.svg',
    new: false,
  },
  {
    navitem: 'Music',
    subname: 'iPod touch',
    img: '/images/music/ipod_touch_light_large.svg',
    new: false,
  },
  {
    navitem: 'Music',
    subname: 'Music Accessories',
    img: '/images/music/accessories_large.svg',
    new: false,
  },
  {
    navitem: 'Music',
    subname: 'Gift Cards',
    img: '/images/music/gift_cards_large.svg',
    new: false,
  },
];
