export const navData = ['Mac', 'iPad', 'iPhone', 'Watch', 'TV', 'Music', 'Support'];

export const subNavData = [
  {
    navitem: 'Mac',
    subname: 'MacBook',
    img: '',
    new: false,
  },
  {
    navitem: 'Mac',
    subname: 'MacBook Air',
    img: '',
    new: false,
  },
  {
    navitem: 'Mac',
    subname: 'MacBook Pro',
    img: '',
    new: true,
  },
  {
    navitem: 'Mac',
    subname: 'iMac',
    img: '',
    new: false,
  },
  {
    navitem: 'Mac',
    subname: 'iMac Pro',
    img: '',
    new: false,
  },
  {
    navitem: 'Mac',
    subname: 'Mac Pro',
    img: '',
    new: false,
  },
  {
    navitem: 'Mac',
    subname: 'Mac mini',
    img: '',
    new: false,
  },
  {
    navitem: 'Mac',
    subname: 'Acccessories',
    img: '',
    new: false,
  },
  {
    navitem: 'Mac',
    subname: 'Mojave',
    img: '',
    new: false,
  },
  {
    navitem: 'Mac',
    subname: 'Compare',
    img: '',
    new: false,
  },
  {
    navitem: 'iPad',
    subname: 'iPad Pro',
    img: '',
    new: false,
  },
  {
    navitem: 'iPad',
    subname: 'iPad',
    img: '',
    new: true,
  },
  {
    navitem: 'iPad',
    subname: 'iPad mini 4',
    img: '',
    new: false,
  },
  {
    navitem: 'iPad',
    subname: 'iOS 12',
    img: '',
    new: false,
  },
  {
    navitem: 'iPad',
    subname: 'Accessories',
    img: '',
    new: false,
  },
  {
    navitem: 'iPad',
    subname: 'Compare',
    img: '',
    new: false,
  },
  {
    navitem: 'iPhone',
    subname: 'iPhone Xs',
    img: '',
    new: true,
  },
  {
    navitem: 'iPhone',
    subname: 'iPhone Xr',
    img: '',
    new: true,
  },
  {
    navitem: 'iPhone',
    subname: 'iPhone 8',
    img: '',
    new: false,
  },
  {
    navitem: 'iPhone',
    subname: 'iPhone 7',
    img: '',
    new: false,
  },
  {
    navitem: 'iPhone',
    subname: 'iOS 12',
    img: '',
    new: false,
  },
  {
    navitem: 'iPhone',
    subname: 'AirPods',
    img: '',
    new: false,
  },
  {
    navitem: 'iPhone',
    subname: 'Accessories',
    img: '',
    new: false,
  },
  {
    navitem: 'iPhone',
    subname: 'Compare',
    img: '',
    new: false,
  },
  {
    navitem: 'Watch',
    subname: 'Apple Watch Series 4',
    img: '',
    new: true,
  },
  {
    navitem: 'Watch',
    subname: 'Apple Watch Nike+',
    img: '',
    new: true,
  },
  {
    navitem: 'Watch',
    subname: 'Apple Watch Hermès',
    img: '',
    new: true,
  },
  {
    navitem: 'Watch',
    subname: 'Apple Watch Series 3',
    img: '',
    new: false,
  },
  {
    navitem: 'Watch',
    subname: 'watchOS',
    img: '',
    new: false,
  },
  {
    navitem: 'Watch',
    subname: 'Bands',
    img: '',
    new: false,
  },
  {
    navitem: 'Watch',
    subname: 'Accessories',
    img: '',
    new: false,
  },
  {
    navitem: 'Watch',
    subname: 'Compare',
    img: '',
    new: false,
  },
  {
    navitem: 'TV',
    subname: 'Apple TV 4K',
    img: '',
    new: false,
  },
  {
    navitem: 'TV',
    subname: 'Apple TV',
    img: '',
    new: false,
  },
  {
    navitem: 'TV',
    subname: 'TV App',
    img: '',
    new: false,
  },
  {
    navitem: 'TV',
    subname: 'Accessories',
    img: '',
    new: false,
  },
  {
    navitem: 'TV',
    subname: 'Compare',
    img: '',
    new: false,
  },
  {
    navitem: 'Music',
    subname: 'Apple Music',
    img: '',
    new: false,
  },
  {
    navitem: 'Music',
    subname: 'iTunes',
    img: '',
    new: false,
  },
  {
    navitem: 'Music',
    subname: 'HomePod',
    img: '',
    new: false,
  },
  {
    navitem: 'Music',
    subname: 'AirPods',
    img: '',
    new: false,
  },
  {
    navitem: 'Music',
    subname: 'iPod touch',
    img: '',
    new: false,
  },
  {
    navitem: 'Music',
    subname: 'Music Accessories',
    img: '',
    new: false,
  },
  {
    navitem: 'Music',
    subname: 'Gift Cards',
    img: '',
    new: false,
  },
];
